name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest
    name: ZAP Baseline Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://url-aplikasi-anda.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'