name: ZAP Baseline Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # === optional: create placeholder files (only needed if you keep -c) ===
      - name: Create placeholder reports (safe)
        run: |
          touch report_json.json report_md.md report_html.html report_xml.xml
          chmod a+w report_*.json report_*.md report_*.html report_*.xml || true

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://reservasihotel.infinityfreeapp.com/customer_dashboard.php'
          # recommended options: -a (active scan), -m (max duration minutes)
          cmd_options: '-a -J report_json.json -w report_html.html -m 20 -r report_md.md -x report_xml.xml'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          fail_action: false
          allow_issue_writing: true
        env:
          # optional envs, keep blank if unused
          ZAP_AUTH_HEADER: ''
          ZAP_AUTH_HEADER_VALUE: ''
          ZAP_AUTH_HEADER_SITE: ''

      - name: Show generated files (debug)
        run: |
          echo "List files in workspace:"
          ls -la
          echo "report_json.json size:"
          if [ -f report_json.json ]; then ls -la report_json.json; else echo "report_json.json NOT FOUND"; fi
          echo "report_html.html size:"
          if [ -f report_html.html ]; then ls -la report_html.html; else echo "report_html.html NOT FOUND"; fi

      - name: Fail if JSON report missing
        if: ${{ always() }}
        run: |
          if [ ! -f report_json.json ] || [ ! -s report_json.json ]; then
            echo "::error file=report_json.json::ZAP JSON report missing or empty. Check target reachability and action logs."
            exit 1
          else
            echo "ZAP JSON found and non-empty. Proceeding."
          fi

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
            report_xml.xml
