name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://reservasihotel.infinityfreeapp.com/customer_dashboard.php"
          cmd_options: "-a -J report_json.json -w report_html.html -m 10 -r report_md.md -x report_xml.xml -c report_csv.csv"

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
            report_xml.xml
            report_csv.csv
