name: ZAP Security Scan with Login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create ZAP context file
      run: |
        cat > zap_context.context << 'EOF'
        <?xml version="1.0"?>
        <context>
          <name>HotelBooking</name>
          <desc>Hotel Booking Application</desc>
          <include-paths>
            <include-path>https://reservasihotel.infinityfreeapp.com/*</include-path>
          </include-paths>
          <authentication>
            <type>form-based</type>
            <login-url>https://reservasihotel.infinityfreeapp.com/login.php</login-url>
            <login-request-data>username={%username%}&amp;password={%password%}</login-request-data>
          </authentication>
          <session-management>
            <method>cookie</method>
          </session-management>
        </context>
        EOF
        
    - name: Create user config
      run: |
        echo "username:${{ secrets.ZAP_USERNAME }}" > user.conf
        echo "password:${{ secrets.ZAP_PASSWORD }}" >> user.conf
        
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'https://reservasihotel.infinityfreeapp.com/'
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        cmd_options: '-a -c zap_context.context -u user.conf'
        issue_title: 'ZAP Security Scan Report'
        fail_action: false
        allow_issue_writing: true
        artifact_name: 'zap-scan-report'
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-results
        path: |
          zap_report.html
          zap_report.md
          zap_report.json