name: ZAP Security Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan with Login
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "https://reservasihotel.infinityfreeapp.com/"
          context_file: ".zap/context.context"
          user: "customer1"
          cmd_options: "-r zap_report.html -J zap_report.json -x zap_report.xml -w zap_report.md"

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.json
            zap_report.xml
            zap_report.md
