name: zap_scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://reservasihotel.infinityfreeapp.com/'
          cmd_options: '-r zap_report.html -w zap_report.md -x zap_report.xml -J zap_report.json -c zap_report.csv'

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v3
        with:
  name: zap_scan_reports
  path: |
    zap/zap_report.html
    zap/zap_report.md
    zap/zap_report.xml
    zap/zap_report.json
    zap/zap_report.csv

